{"uuid": "6c2dd653-dbd4-45f9-bd1e-b0c19430ad4f", "children": ["71075f69-42ea-4a53-8cfe-661b3b9e5c10", "9988161c-9905-465b-9d99-2a3a8b8accbb", "0bcc60aa-6e11-4c28-bb85-04d7b95dedb4", "4327101a-916c-4e1a-9279-2821cfde2965", "31b3cffd-ccc5-44cd-9735-f2e1fd661088", "745e4b9e-d355-47ef-ba11-bb3006bf3b41"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "f904c2a0-bf80-458c-a34e-fc385cde59a5-attachment.attach"}, {"name": "Time Took to apply Config: 173.05310344696045", "source": "06ddb85e-5f31-4b27-8392-8fea11bc2c6c-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "ce11f17d-b5b7-48b5-ae7e-3ab0eee27819-attachment.attach"}, {"name": "AP LOgs: ", "source": "f02be74a-478a-4caf-9d0e-1d3f61daa38d-attachment.attach"}], "start": 1628987499439, "stop": 1628987702357}], "start": 1628987499439, "stop": 1628987702819}