{"uuid": "c1971661-773a-4cbb-bf67-005e668a8106", "children": ["09983a44-bde6-4d16-966c-39fb442884ae", "1938220c-8bd3-48d6-a744-0e04b6ae4a0c", "cebbca9a-3998-47b3-83bb-8d20aed12939", "2230fb4c-9b9b-41f1-9ea9-4f8db3afa499", "8d43fca2-7c77-46b6-a321-e42c2851577a", "01f1bfa3-ea0b-4d5e-9506-bbc994fcdc27"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "a18b494b-0a91-4e83-a8e9-782215531154-attachment.attach"}, {"name": "Time Took to apply Config: 101.11331725120544", "source": "59667f79-22dc-4d28-ae3b-dd10c93b3e5f-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "36a230c7-db42-46f8-b114-6962a0617b5c-attachment.attach"}, {"name": "AP LOgs: ", "source": "5c32bf84-ddab-49d9-afaf-e8b6276af77c-attachment.attach"}], "start": 1628987189204, "stop": 1628987319886}], "start": 1628987189204, "stop": 1628987320497}