{"uuid": "a31c6e1a-2e68-4e72-b403-4e8d65372588", "children": ["61d0733b-6a9f-4898-8790-5ae9fbb08feb", "ef6f22dc-0cb0-4b0b-9bdf-2af941a79607", "f0afbe81-96dd-44f5-a57b-a0fc4d9029bd", "8c6f8121-2f1c-4255-9c30-5e3b574bf1cb", "32e3737b-b1ca-4092-abbd-d294352e45cf", "7cbed12f-83f6-44b0-9e24-d3afccd13284"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "50e792af-ff11-4518-8425-b0688ad308c8-attachment.attach"}, {"name": "Time Took to apply Config: 149.386878490448", "source": "9dd1b6a4-12e9-4d31-9554-9ce22e4b232b-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "62caf2e1-5e58-47b3-8d01-8cf265c3ebd7-attachment.attach"}, {"name": "AP LOgs: ", "source": "cff85659-42d6-406e-afe2-3adb6ec4f7fe-attachment.attach"}], "start": 1628988145588, "stop": 1628988334729}], "start": 1628988145588, "stop": 1628988335145}