{"uuid": "1a2cd949-5261-4436-84d5-65bd65c3c592", "children": ["6e9ce0a6-d590-4cc9-b5d8-563784b47a99", "a83b7ac7-c2a5-4d5b-bb96-ff8d595686dc", "7ff85b3f-d53f-461a-a11e-2e9503efaa53", "d3609027-eefe-4d09-9145-495fde7c863a", "fb8ee7ce-119d-409c-96c8-d68b7d0349b8", "0444c809-1d0e-442c-95fa-fe9790fa149f"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 401, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], j[\"config\"][\"key\"]]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "4c5feb6a-8594-4e7e-8476-735a47667ba8-attachment.attach"}, {"name": "Time Took to apply Config: 73.09916114807129", "source": "7d002456-c997-4285-9b63-d579a1ee1286-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "e2ecf603-9095-45a0-88d0-7d7611405e79-attachment.attach"}, {"name": "AP LOgs: ", "source": "f7017e38-c7c8-4d36-8e76-e639acc536e9-attachment.attach"}], "start": 1629073856998, "stop": 1629073959334}], "start": 1629073856998, "stop": 1629073959739}