{"uuid": "2eb7f39e-a4a0-4e10-8c4d-6378a4644307", "children": ["74e90bf7-2198-40a7-9b5e-ceab8942de35"], "befores": [{"name": "instantiate_access_point", "status": "broken", "statusDetails": {"message": "paramiko.ssh_exception.SSHException: No existing session\n", "trace": "  File \"/home/nikita/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/nikita/candela_projects/rate-vs-range/wlan-testing/tests/conftest.py\", line 219, in instantiate_access_point\n    get_apnos(access_point_info, pwd=\"../libs/apnos/\")\n  File \"/home/nikita/candela_projects/rate-vs-range/wlan-testing/tests/../libs/apnos/apnos.py\", line 34, in __init__\n    client = self.ssh_cli_connect()\n  File \"/home/nikita/candela_projects/rate-vs-range/wlan-testing/tests/../libs/apnos/apnos.py\", line 65, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/usr/lib/python3/dist-packages/paramiko/client.py\", line 412, in connect\n    server_key = t.get_remote_server_key()\n  File \"/usr/lib/python3/dist-packages/paramiko/transport.py\", line 834, in get_remote_server_key\n    raise SSHException(\"No existing session\")\n"}, "attachments": [{"name": "added openwrtctl.py to :", "source": "31c3e964-1dcd-495c-bbfc-e763a4d46cd2-attachment.attach"}, {"name": "APNOS LIbrary: ", "source": "b577a6d4-6c35-4176-8caa-f5251b1f0c7b-attachment.attach"}], "start": 1626064655024, "stop": 1626064665044}], "start": 1626064655024, "stop": 1626064665232}