{"uuid": "4f4d4d0d-5a7c-473c-9c4c-04a680ece406", "children": ["7990a059-b204-4c54-9869-67aa6d7e301e"], "befores": [{"name": "instantiate_access_point", "status": "broken", "statusDetails": {"message": "paramiko.ssh_exception.SSHException: No existing session\n", "trace": "  File \"/home/nikita/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/nikita/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/nikita/candela_projects/rate-vs-range/wlan-testing/tests/conftest.py\", line 219, in instantiate_access_point\n    get_apnos(access_point_info, pwd=\"../libs/apnos/\")\n  File \"/home/nikita/candela_projects/rate-vs-range/wlan-testing/tests/../libs/apnos/apnos.py\", line 34, in __init__\n    client = self.ssh_cli_connect()\n  File \"/home/nikita/candela_projects/rate-vs-range/wlan-testing/tests/../libs/apnos/apnos.py\", line 65, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/usr/lib/python3/dist-packages/paramiko/client.py\", line 412, in connect\n    server_key = t.get_remote_server_key()\n  File \"/usr/lib/python3/dist-packages/paramiko/transport.py\", line 834, in get_remote_server_key\n    raise SSHException(\"No existing session\")\n"}, "attachments": [{"name": "added openwrtctl.py to :", "source": "4d7ab7b4-7571-472c-acc4-c7a4b3868fe0-attachment.attach"}, {"name": "APNOS LIbrary: ", "source": "1d869da8-5f1e-4972-9686-a52b1c103736-attachment.attach"}], "start": 1626065000533, "stop": 1626065010558}], "start": 1626065000533, "stop": 1626065010711}