{"uuid": "afd28d3a-387e-4e20-b5c4-44bb9fdba284", "children": ["d13081ee-9816-4841-8212-12ce05fef5f0", "753bddbd-98d9-46ae-ab8d-ffd1603919f7", "8cfbe85d-70a3-4bfe-a460-3e95f84b38fc", "864f3ee9-5901-4f79-a9c4-7415b2909c44", "f53f6a01-9928-44bb-9696-d7ef9a303554", "9e278f8d-cd95-49f1-9d7c-bad5eba029b0"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "91e163c8-7bed-48fc-8dea-b2165aa0ba66-attachment.attach"}, {"name": "Time Took to apply Config: 83.66045594215393", "source": "92cf2dfb-bd60-4c2f-920b-8815acd12bfa-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "5a69feaf-98c3-4b24-99a1-6fbbd81b4a51-attachment.attach"}, {"name": "AP LOgs: ", "source": "1e21d396-ef13-4f1b-a064-f737387ed2a4-attachment.attach"}], "start": 1628902180952, "stop": 1628902293734}], "start": 1628902180952, "stop": 1628902294173}