{"uuid": "1e70f03c-9431-4d06-8980-ba4ed4ecf56c", "children": ["74e12392-b4a1-43cf-9877-b244df9f18e3", "c1b5885a-3477-4378-974f-901ec6befa1a", "3699da8f-6d2e-4386-b3ac-c285f77dacf6", "0c744fe5-e0e5-4c25-82e6-04f84d471b40", "e00a8bae-bfa6-40a0-83b0-0ac4b978a843", "ab4451c6-f6e4-43d3-a622-53600e6bed7f"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 80, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 389, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], j[\"config\"][\"key\"]]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "26fd4b4a-d20a-4c4d-86ba-ecd98763618f-attachment.attach"}, {"name": "Time Took to apply Config: 40.980600357055664", "source": "57e0ca0f-a8c1-4c75-94e2-d47ec7203220-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "52208824-3d1c-48ff-a1e8-bff914a8605c-attachment.attach"}, {"name": "AP LOgs: ", "source": "8faaa42e-39af-41a3-a440-4b74d556b6b2-attachment.attach"}], "start": 1628556625395, "stop": 1628556695864}], "start": 1628556625395, "stop": 1628556696379}