{"uuid": "a90602f3-63ca-4099-8c8a-24fcab176842", "children": ["21d45c79-0a7c-4edb-96ca-ff356767bb81", "4af62ec2-3c19-401f-a546-ee659e1a26af", "05d1ccd1-749b-49a6-b07d-353501a7ae4e", "bde2c44a-3dcd-4cb7-83b8-2660f3db56b7", "63776beb-bbd8-4faa-b779-5a5b5dc92f5a", "e2349cdc-3f5d-45b4-97c4-45be58dd6e54"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 80, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 389, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], j[\"config\"][\"key\"]]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "a6068938-a820-4b6b-8632-2133ab1cd89b-attachment.attach"}, {"name": "Time Took to apply Config: 56.97324180603027", "source": "e8890aa0-420f-42c0-9db7-1c7392a6ed3f-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "c3ae819c-a971-4488-abe9-572e2fb7fe4c-attachment.attach"}, {"name": "AP LOgs: ", "source": "457600c2-03b1-44c1-88d2-06b784c802d2-attachment.attach"}], "start": 1628556895333, "stop": 1628556990826}], "start": 1628556895333, "stop": 1628556991252}