{"uuid": "c1ef717b-2b5b-4fec-8e3d-6e949088e39e", "children": ["dede04a8-d941-4a77-bade-61bb66ccd4f1", "4e16f9ab-4e7f-4a1f-ad2a-487a35099301", "6b20c5f5-5cd2-48cd-90da-1087f8f160ac", "98ec4c94-36e1-405d-9bcd-c7c0fc47cb7d", "9feb7041-f73e-489b-84ee-6508a8176e28", "7e7ce86c-1d9b-4a0a-8c92-2b6caeeb4f2d"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'wlan0-1'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 408, in get_interface_details\n    wifi_info[i].append(data[i])\n"}, "attachments": [{"name": "ucentral_config: ", "source": "938d1577-cbc8-406c-9661-272dab6fa8b9-attachment.attach"}, {"name": "Time Took to apply Config: 40.139575242996216", "source": "a55c21f9-6670-480b-badb-08a205e760e8-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "d5d09b20-c8f6-4dd0-83ea-758f1981cdae-attachment.attach"}, {"name": "AP LOgs: ", "source": "1ff81023-897e-4fe2-9074-626b0e280576-attachment.attach"}], "start": 1629419345211, "stop": 1629419417133}], "start": 1629419345211, "stop": 1629419417778}