{"uuid": "df1f935f-2ac9-4463-a798-a18b37b72763", "children": ["a273d307-64d6-4f8b-916d-617e39f99bd9", "9863b4e8-c6fb-42a2-a722-b767226bb882", "c27c6f0e-97ef-44ed-aa23-3b9b1c926132", "676042d8-7d11-4d70-b549-faf3d119467d", "9819ca5e-68e9-4927-953a-9e5de8119b65", "624301e1-ef26-4abf-817f-5b93e8b5d487"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 401, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], j[\"config\"][\"key\"]]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "578c8b21-024a-4ea1-af9f-3e99a5cda70b-attachment.attach"}, {"name": "Time Took to apply Config: 33.89569711685181", "source": "3e581a5b-7b19-49d0-bbc9-bd5302f0dfeb-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "d9d73116-7a1e-45cd-8223-d2a63e17e18f-attachment.attach"}, {"name": "AP LOgs: ", "source": "6eff5268-3038-4079-a3ed-f90c35de3b83-attachment.attach"}], "start": 1629160046436, "stop": 1629160112700}], "start": 1629160046436, "stop": 1629160113153}