{"uuid": "27be272e-12ea-48aa-9cfa-bd01d632622c", "children": ["66873bfc-4fcb-4d60-92c2-0793318d28f1", "e5e4a533-4cae-4bc9-8f4e-23f158b0d1c2", "ec26a3d0-0cac-49d5-8614-ecd46f20ba51", "45638a80-9bea-4225-99cd-166d0e316514", "c963106d-02f9-4ad1-ba7c-1b748d0c25f1", "d9610c33-7e2d-4bcb-a32c-d6fd151ffa12"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "48173f60-3c8d-4ac1-9297-971c9384c519-attachment.attach"}, {"name": "Time Took to apply Config: 44.69931101799011", "source": "f8f01589-3e99-4e41-8407-26aaa88b0dd3-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "3715eec9-7e38-41a4-b622-b5d564a627d0-attachment.attach"}, {"name": "AP LOgs: ", "source": "54cad220-b9f2-4b05-b227-efe499f5f785-attachment.attach"}], "start": 1629160178135, "stop": 1629160251729}], "start": 1629160178135, "stop": 1629160252564}