{"uuid": "0ca0fac8-651f-489b-8839-e3acac86c12e", "children": ["ee805aa9-e58f-4e1a-905a-9b5cd2faaca5", "01245a03-1b02-40b2-a54f-171ba30ade8f", "3696352f-7eef-492c-9fd9-155996762e1d", "24495000-242d-41c2-91b9-fab6a3eb7f07", "ca3e1177-bf68-41e0-8b92-49753864bd95", "c8217b78-f5d2-45b0-9e65-cadded36d964"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "2f3d7389-8187-43a9-8e0d-b0d02d23d490-attachment.attach"}, {"name": "Time Took to apply Config: 56.64059400558472", "source": "3a1fc121-43df-471e-9ae1-dced532ae70b-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "093425e4-c916-416d-beda-341ca544d3f5-attachment.attach"}, {"name": "AP LOgs: ", "source": "c1425420-b392-469d-b0c3-3b71ec7e9bac-attachment.attach"}], "start": 1629160241454, "stop": 1629160327316}], "start": 1629160241454, "stop": 1629160327671}