{"uuid": "0d478f24-e300-4c1b-aa2d-57faec03d41b", "children": ["2d56b5dd-9d92-41d8-8eae-948f3bc7559e", "a4b62c7b-b5c7-4f1a-aa0c-4061e53c77f8", "85174d41-5715-4775-bb06-eea1a79ac842", "68f4a604-5c2b-43a4-98a6-26f30379b734", "0b8971e9-c013-4911-a488-3e814d9a8046", "ea61168e-a411-49ca-bad3-73d6fb78a0da"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "c6c36075-424c-4660-ae16-a748a39a0d21-attachment.attach"}, {"name": "Time Took to apply Config: 35.11258006095886", "source": "507152a3-bad3-40e8-98a4-5ba297f54e02-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "2bad87dd-ab03-4378-b5a4-4c5619ada47c-attachment.attach"}, {"name": "AP LOgs: ", "source": "b060981c-aa7a-4348-bd1e-4b60f08bcfc4-attachment.attach"}], "start": 1629160105756, "stop": 1629160170009}], "start": 1629160105756, "stop": 1629160170293}