{"uuid": "2a83c086-7630-4414-b3a6-12c45f633bb4", "children": ["36968622-da21-43d4-b79c-56c8e460367d", "73754e2b-2dab-4272-a375-c2f55acb7dd7", "09961986-7c04-4eb4-abc4-7312d15ae8cf", "e7f8e775-4a3b-4883-9636-a0f532e9aa2a", "ec11ef8f-f2e2-474f-984f-417620d72840", "53035a94-6e6f-4378-a934-1d0cb3c058f7"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 401, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], j[\"config\"][\"key\"]]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "87870467-85bd-41ad-b8cc-e1786ba210a2-attachment.attach"}, {"name": "Time Took to apply Config: 99.56376194953918", "source": "5708923b-2339-44b7-9ac0-678df11a9a73-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "ebb93a2f-3b1a-410c-83ff-ff2c16e62f29-attachment.attach"}, {"name": "AP LOgs: ", "source": "1144e055-467f-4826-af3b-280d151060a6-attachment.attach"}], "start": 1629073813392, "stop": 1629073941429}], "start": 1629073813392, "stop": 1629073941836}